### ISSUE TITLE
Remove Android Icon

### ISSUE THREAD

**Issue by rayliverified** [Shashank02051997/FancyToast-Android#1]
Amazing looking toasts! I love the raised bubbly look. It is perfect for a certain style of apps and has not been shared on Github before. Thank you! 

Is it possible to provide an option to remove the Android Icon in the top right corner of the toasts? That icon is somewhat distracting. Thank you!

**Comment by AbdullahAlAsad** [comment]
Yes Amazing toasts. Can we try to remove or make the top right android icon optional. Again thank you for your amazing work.,

**Comment by Shashank02051997** [comment]
Thank u for ur support. I will definitely add this feature to this library so u can add or remove the icon on top right hand side one.

**Comment by yaqubpatel2233** [comment]
thank you to make our toast colorful and fancy...good work...only thing to suggest please remove top right android icon...

**Comment by Shashank02051997** [comment]
Check out the latest version of Fancy Toast where you can able to remove the android icon on top-right corner by passing last parameter false.

**Comment by yaqubpatel2233** [comment]
Thanks for update...
