### ISSUE TITLE
does not work with compileSdkVersion 27 and minSdkVersion 15

### ISSUE THREAD

**Issue by jcarlos79t** [Shashank02051997/FancyToast-Android#10]
I love your library but it does not work in compileSdkVersion 27 and minSdkVersion 15, any way it works in the future ??

**Comment by Shashank02051997** [comment]
No plans to make for version 15. It is now compatible for min 21 API level. Please check it out now

**Comment by Shashank02051997** [comment]
Please check out the new version of this lib, i have downgrade it for API level 15.
