### ISSUE TITLE
Why FancyToast class is extending Toast class?

### ISSUE THREAD

**Issue by khawarraza-netsoltech** [Shashank02051997/FancyToast-Android#11]
I don't know why FancyToast class is extending from Toast class when your class is using static method and using default Toast class to do all the stuff?

**Comment by Shashank02051997** [comment]
Because of the Toast class the base class which gives the functionality to modify their methods and also we can modify the toast UI that's why i am extending the Toast class.

**Comment by khawarraza-netsoltech** [comment]
You don't need to extend FancyToast from Toast if you never intend to create object of FancyToast class.
