### ISSUE TITLE
Migration to AndroidX

### ISSUE THREAD

**Issue by MonikaJethani** [Shashank02051997/FancyToast-Android#14]
@Shashank02051997 Can I work on this?

**Comment by Shashank02051997** [comment]
Yeah Sure

**Comment by MonikaJethani** [comment]
@Shashank02051997 Please review this PR- https://github.com/Shashank02051997/FancyToast-Android/pull/15

**Comment by Shashank02051997** [comment]
Done @MonikaJethani thanks
