### ISSUE TITLE
Error in app gradle while sync

### ISSUE THREAD

**Issue by rahulmanek** [Shashank02051997/FancyToast-Android#16]
ERROR: Failed to resolve: com.github.Shashank02051997:FancyToast-Android:0.1.6
Show in Project Structure dialog
Affected Modules: app

**Comment by 0x8BADFOOD** [comment]
How that was resolved?
Ok just need to insert it (` maven { url "https://jitpack.io" }`)in` both places buildscrip and allprojects.
```
buildscript {
    repositories {
...
        maven { url "https://jitpack.io" }
        
    }
   ...
allprojects {
    repositories {
      
        maven { url "https://jitpack.io" }

    }
}
```
