### ISSUE TITLE
Using Gravity

### ISSUE THREAD

**Issue by PassionateSolutions** [Shashank02051997/FancyToast-Android#18]
Using Gravity within the Toast makes .show() come up red:

FancyToast.makeText(Login.this, "Welcome!  Please Login", FancyToast.LENGTH_SHORT, FancyToast.INFO, false).setGravity(Gravity.CENTER_HORIZONTAL, 0, 0).**show()**;

**Comment by PassionateSolutions** [comment]
SOLUTION:

Toast toast = FancyToast.makeText(Login.this, "Welcome!  Please Login", FancyToast.LENGTH_SHORT, FancyToast.INFO, false);
        toast.setGravity(Gravity.CENTER, 0, 0);
        toast.show();

**Comment by Shashank02051997** [comment]
Hi @PassionateSolutions actually I didn’t get your issue.
