### ISSUE TITLE
How to change duration?

### ISSUE THREAD

**Issue by rezasys2** [Shashank02051997/FancyToast-Android#22]
Hello there,
I want to change the duration value but when I set it to an integer value, it doesn't work. The duration is the same as the default.

**Comment by Shashank02051997** [comment]
Hey, @rezasys2 thanks for using the fancy toast lib. Yes, many there is some issue in it. I will try to fix this in the new release.

**Comment by Shashank02051997** [comment]
@rezasys2 try to implementation 'com.github.Shashank02051997:FancyToast-Android:0.1.8'. Let me know if you are still facing the same issue in this version

**Comment by rezasys2** [comment]
Thanks for your attention, but I realized while you are using "Toast" the only possible durations are SHORT and LONG, there is no more option. I mean you can not use integer, it won't work anyway.

**Comment by Shashank02051997** [comment]
@rezasys2 I am closing this issue for now.

**Comment by sagar0701** [comment]
Hi duration int value still not working could you suggest?
