### ISSUE TITLE
duration not working please advise.

### ISSUE THREAD

**Issue by sagar0701** [Shashank02051997/FancyToast-Android#26]
Used newer as well as older version both having same issue.
    //implementation 'com.github.Shashank02051997:FancyToast-Android:0.1.8'
    implementation 'io.github.shashank02051997:FancyToast:2.0.1'

 FancyToast.makeText(getApplicationContext(), msg,5000 , FancyToast.SUCCESS, false).show();

**Comment by Shashank02051997** [comment]
@sagar0701 In android Toast you cannot pass duration like this... you need to send the duration like FancyToast.LENGTH_LONG

**Comment by Shashank02051997** [comment]
@sagar0701 I am closing this issue feel free to reopen it again
