### ISSUE TITLE
can you give us a way to colorize the toasts?

### ISSUE THREAD

**Issue by Photogad** [Shashank02051997/FancyToast-Android#5]

**Comment by Shashank02051997** [comment]
Ok i will try to update this thing

**Comment by Photogad** [comment]
Much appreciated. I love this library

**Comment by Adarshkl** [comment]
yea. Some means to customize the toast colors would be great.

**Comment by Shashank02051997** [comment]
Hey guys,

Sorry for the late reply. I have tried to customize the toast color, it is customizable if we remove the shadow from the toast. So for now i am closing the issue and if i will find the best solution for customizing the toast color i will definitely add to this library
