### ISSUE TITLE
Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 19 declared

### ISSUE THREAD

**Issue by waseefakhtar** [Shashank02051997/FancyToast-Android#8]
Are there any plans to make FancyToast version 15 compatible in the future?

**Comment by Shashank02051997** [comment]
No plans to make for version 15. It is now compatible for min 21 API level.

**Comment by Shashank02051997** [comment]
Please check out the new version of this lib, i have downgrade it for API level 15.

**Comment by waseefakhtar** [comment]
Awesome, thanks!
